before_script:
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

test:
  script:
    - bundle exec rspec
  only:
    - branches

validate_changelog:
  script:
    - gem build parse_a_changelog.gemspec
    - gem install --force --local parse_a_changelog-$(cat VERSION).gem
    - parse ./CHANGELOG.md
  only:
    - branches
